### ISSUE TITLE
Whisper optimization using ORT toolchain

### ISSUE THREAD

**Issue by reeselevine** [microsoft/Olive#1264]
**Describe the bug**
Following the instructions as written at https://github.com/microsoft/Olive/tree/main/examples/whisper does not work as they are written.

I'm following the instructions at https://github.com/microsoft/onnxruntime-inference-examples/tree/main/js/ort-whisper to try out onnxruntime form the web. However, when I run this command:

```
python -m olive.workflows.run --config whisper_cpu_int8.json --setup
```
after installing requirements using `python -m pip install -r requirements.txt`, I get these messages:

```
[WARNING] [run.py:347:check_local_ort_installation] There are one or more onnxruntime packages installed in your environment!
The setup process is stopped to avoid potential conflicts. Please run the following commands manually:
Uninstall all existing onnxruntime packages: '/Users/reeselevine/miniconda3/bin/python -m pip uninstall -y onnxruntime onnxruntime_extensions'
Install onnxruntime: '/Users/reeselevine/miniconda3/bin/python -m pip install onnxruntime'
```

However, if I do not have `onnxruntime_extensions` installed, then running `python -m olive.workflows.run --config whisper_cpu_int8.json` fails.

The solution seems to be to install all requirements, remove `onnxruntime_extensions`, run the setup, re-install `onnxruntime_extensions`, then run the optimization. However, this seems clunky and wrong, so thought I'd make this issue to see if there is something up with the code and/or README instructions.

I also had to install `onnxruntime` separate from the instructions on that page, it looks like the package was removed from `requirements.txt` recently.

**Other information**
 - OS: OSX
 - Olive version: main
 - ONNXRuntime package and version: onnxruntime-1.18.1

**Comment by xiaoyu-work** [comment]
Hi, Olive doesn't have the ability to handle the case where multiple onnxruntime packages are already installed in the environment, so that's why there is a warning like that. That warning means user should uninstall all onnxruntime related packages and reinstall the onnxruntime packages. 

But you are right `onnxruntime_extensions` shouldn't be here in the warning message, this only handles onnxruntime packages. This warning message is confusing. I'll fix this. Thanks for reporting this! 

The correct order should be: run --setup command to install required packages -> saw warning message -> uninstall onnxruntime by the command from the warning message -> install the onnxruntime by the command from the message.

**Comment by xiaoyu-work** [comment]
Code had been merged. Closing.
