### ISSUE TITLE
How to append custom parameter ActivationSymmetric=True to extra_options

### ISSUE THREAD

**Issue by zz002** [microsoft/Olive#139]
#### How to append custom parameter `ActivationSymmetric=True` to `"extra_options"`？

In the following code, the custom parameter `ActivationSymmetric` does not start with `"eo_"`.

https://github.com/microsoft/Olive/blob/main/olive/passes/onnx/quantization.py#L283

**Comment by jambayk** [comment]
Thanks for bringing this up. For Olive passes, the user cannot provide custom parameters. The only supported parameters for a pass are those in the `_default_config` dict which are also listed on out `Pass` [api reference here](https://microsoft.github.io/Olive/api/passes.html#onnxquantization). Any parameter that is not part of the supported parameters are ignored during (config validation)[https://github.com/microsoft/Olive/blob/main/olive/passes/olive_pass.py#L45]

Currently our quantization passes don't have any of the `extra_options` parameters supported. This would need us to update the passes to add them to their `_default_config` dicts. 

The code you have pointed to are actually not used at all since we don't have any of the `extra_options` as part of our pass config. Our original intention was to prefix all `extra_options` parameters with `eo_` to make it easy to distinguish them. But as you pointed out, there is a bug here where we are not removing the prefix afterwards. 

We do plan to add the extra option parameters to our passes.

**Comment by jambayk** [comment]
Hi, this issue was auto-resolved by the linked PR. `ActivationSymmetric` is now a config parameter so you can set it to False in your  pass config json/dict.
