### ISSUE TITLE
[FR]: Shared cache when running on Azure Machine Learning compute

### ISSUE THREAD

**Issue by cecheta** [microsoft/Olive#1508]
### Proposal Summary

When using the CLI commands, `exclude_managed_identity_credential` is always set to `True`, meaning that if you are running a command on a compute instance with a managed identity in Azure Machine Learning, then it isn't possible to authenticate with Azure Storage, and you cannot use shared cache. Is this deliberate?

### What component(s) does this request affect?

- [ ] OliveModels
- [ ] OliveSystems
- [ ] OliveEvaluator
- [ ] Metrics
- [ ] Engine
- [ ] Passes
- [x] Other

**Comment by xiaoyu-work** [comment]
Do you mean the CLI command that is using shared-cache, or the shared-cache deletion CLI? For the first case, it doesn't set any default auth params. For the second case, in most of the cases this CLI will be run manually, while if people run this on AML compute, since we use `DefaultAzureCredential` by default, `ManagedIdentityCredential` will be used before `AzureCliCredential` (from `az login`), and this credential from AML compute usually doesn't have permission for storage operation. We expect users run `az login` and use their own identity credential for this storage operation.

**Comment by cecheta** [comment]
Apologies, seems like the issue was actually with the permissions on the compute instance
