### ISSUE TITLE
[FR]: About path.

### ISSUE THREAD

**Issue by lshqqytiger** [microsoft/Olive#675]
### Proposal Summary

Olive is importing its local files as follows.
```py
from benchmark_helper import Precision, setup_logger
from fusion_utils import NumpyHelper
from models.gpt2.convert_to_onnx import main as convert_gpt2_to_onnx
from models.gpt2.gpt2_helper import PRETRAINED_GPT2_MODELS
from models.t5.convert_to_onnx import export_onnx_models as export_t5_onnx_models
from models.t5.t5_helper import PRETRAINED_MT5_MODELS, PRETRAINED_T5_MODELS
```
However, this is likely to cause `ModuleNotFoundError` when Olive is used as a module.
If I have 'models' folder in my application, I got `ModuleNotFoundError: No module named 'models.gpt2'`.
How about importing them like `from .models...`?

### What component(s) does this request affect?

- [ ] OliveModels
- [ ] OliveSystems
- [ ] OliveEvaluator
- [ ] Metrics
- [ ] Engine
- [ ] Passes
- [X] Other

**Comment by jambayk** [comment]
These imports are coming from `onnxruntime` which is an external dependency for olive. Because of this, there is nothing that we can do from our side to avoid this other than to avoid having local directories with the same name. 
Related to a previous issue https://github.com/microsoft/Olive/issues/554

**Comment by lshqqytiger** [comment]
Oh got it. Sorry for submitting on wrong repository. I had to check the file path.
